import pandas as pd

gold_path = "data/gold_annotations.csv"

df = pd.read_csv(gold_path, dtype={"annotation_id": str})

for col in ["requirement_type", "importance", "resume_evidence", "label", "evidence_start", "evidence_end", "notes"]:
    df[col] = df[col].astype("object")

annotations = {
    1:  ("soft_skill", "unspecified", "Excellent communication and interpersonal skills", "Strong"),
    2:  ("tool", "unspecified", "Adept at using Microsoft Excel, Microsoft PowerPoint, Microsoft Word", "Partial"),
    3:  ("experience", "unspecified", "Senior Analyst – Business Development & Marketing, Aug 2020 – Present", "Strong"),
    4:  ("education", "unspecified", "Bachelors in Business Administration (Honors) 2014", "Strong"),
    5:  ("education", "unspecified", "Bachelors in Business Administration (Honors) June 2021", "Strong"),
    6:  ("soft_skill", "unspecified", "Excellent Verbal and written communication", "Strong"),
    7:  ("education", "unspecified", "B.COM Bachelors of Commerce: Commerce & IT", "Partial"),
    8:  ("capability", "unspecified", "Managing Multiple Projects", "Strong"),
    9:  ("tool", "unspecified", "Excellent MS Office and presentation skills", "Partial"),
    10: ("education", "unspecified", "Bachelors in Business Administration (Honors) June 2021", "Strong"),

    11: ("tool", "unspecified", "", "Unsupported"),
    12: ("soft_skill", "unspecified", "Strategic Planning", "Strong"),
    13: ("soft_skill", "unspecified", "Ability to interact and effectively communicate with people from diverse backgrounds", "Strong"),
    14: ("capability", "unspecified", "Ability to Multitask", "Partial"),
    15: ("tool", "unspecified", "", "Unsupported"),
    16: ("tool", "unspecified", "Managing business and Leads using Hubspot", "Partial"),
    17: ("experience", "unspecified", "Business Development Officer — January 2019 to Present", "Strong"),
    18: ("responsibility", "unspecified", "Generating leads and sharing lead assignments with our on-shore department", "Strong"),
    19: ("education", "unspecified", "B. Com", "Partial"),
    20: ("experience", "unspecified", "Sales Specialist — Cisco Systems Inc", "Strong"),

    21: ("capability", "unspecified", "Team leadership and mentoring responsibilities", "Strong"),
    22: ("technical_skill", "unspecified", "Business development and planning", "Partial"),
    23: ("tool", "unspecified", "Microsoft Office and CRM systems", "Strong"),
    24: ("soft_skill", "unspecified", "Critical and creative thinking; Business Analysis and Process Management", "Strong"),
    25: ("responsibility", "unspecified", "Sales roles and client relationship management", "Strong"),
    26: ("responsibility", "unspecified", "Lead generation and client engagement experience", "Strong"),
    27: ("education", "unspecified", "Bachelor of Business Administrations", "Strong"),
    28: ("tool", "unspecified", "Salesforce/SFDC experience", "Partial"),
    29: ("capability", "unspecified", "Project management and multiple concurrent responsibilities", "Strong"),
    30: ("education", "unspecified", "BS Computer Science", "Partial"),

    31: ("education", "unspecified", "B.S. in Information Technology", "Partial"),
    32: ("experience", "unspecified", "Business Development Executive / BDE experience", "Partial"),
    33: ("tool", "unspecified", "MS Office", "Partial"),
    34: ("responsibility", "unspecified", "Business Development/Sales and client-facing experience", "Partial"),
    35: ("education", "unspecified", "", "Unsupported"),
    36: ("experience", "unspecified", "Business Development at Odetta.ai since 11/2018", "Strong"),
    37: ("tool", "unspecified", "Power BI; Business Analytics; Data Analytics", "Strong"),
    38: ("education", "unspecified", "B.Com", "Partial"),
    39: ("education", "unspecified", "Bachelor in Commerce", "Partial"),
    40: ("tool", "unspecified", "Zoho CRM; MS Office", "Strong"),
    41: ("responsibility", "unspecified", "Lead generation and client engagement", "Strong"),
    42: ("technical_skill", "unspecified", "", "Unsupported"),
    43: ("tool", "unspecified", "", "Unsupported"),
    44: ("experience", "unspecified", "Business development and sales management experience", "Partial"),
    45: ("soft_skill", "unspecified", "Strategic business planning, sales forecasting and market analysis", "Strong"),
    46: ("tool", "unspecified", "", "Unsupported"),
    47: ("education", "unspecified", "Bachelors of Business Administration (B.B.A.) - Sales & Marketing", "Strong"),
    48: ("education", "unspecified", "Bachelors of Business Administration (B.B.A.) - Sales & Marketing", "Strong"),
    49: ("experience", "unspecified", "Extensive business development experience", "Strong"),
    50: ("tool", "unspecified", "Adept in Microsoft Word & PowerPoint", "Strong"),
    51: ("education", "unspecified", "", "Unsupported"),
    52: ("education", "unspecified", "", "Unsupported"),
    53: ("education", "unspecified", "", "Unsupported"),
    54: ("education", "unspecified", "B.Sc. (Hons) in Economics", "Partial"),
    55: ("education", "unspecified", "", "Unsupported"),
    56: ("education", "unspecified", "", "Unsupported"),
    57: ("education", "unspecified", "B.com, Punjab Group of Colleges", "Partial"),
    58: ("education", "unspecified", "Bachelor of Business Administrations | Institute of Business Administration, Karachi | 2016-2020", "Strong"),
    59: ("education", "unspecified", "Masters of Practicing Accounting, Swinburne University of Technology, 2017", "Strong"),
    60: ("education", "unspecified", "Bachelor of Commerce in Information Technology", "Partial"),
    61: ("education", "unspecified", "Bachelor of Business Administration (BBA), Accounting and Finance", "Strong"),
    62: ("education", "unspecified", "BSCS, COMSATS University Islamabad", "Partial"),
    63: ("education", "unspecified", "", "Unsupported"),
    64: ("education", "unspecified", "BBA (Honors), Lahore School of Economics", "Strong"),
    65: ("education", "unspecified", "", "Unsupported"),
    66: ("education", "unspecified", "B.Com., University of the Punjab, 2017", "Partial"),
    67: ("education", "unspecified", "M.Sc. (Economics), Bahauddin Zakariya University", "Partial"),
    68: ("education", "unspecified", "B.Sc. (Honors), Business Accounting and Finance", "Strong"),
    69: ("education", "unspecified", "", "Unsupported"),
    70: ("education", "unspecified", "B.Com., Punjab University", "Partial"),
    71: ("education", "unspecified", "", "Unsupported"),
    72: ("education", "unspecified", "Bachelor of Arts (Business Subjects), Allama Iqbal Open University, 2002", "Partial"),
    73: ("education", "unspecified", "BBA", "Strong"),
    74: ("education", "unspecified", "", "Unsupported"),
    75: ("education", "unspecified", "BS - Operations Management (HONS)", "Partial"),
    76: ("education", "unspecified", "Bachelor of Commerce (BCOM-IT), 2008", "Partial"),
    77: ("education", "unspecified", "", "Unsupported"),
    78: ("education", "unspecified", "BS (Hons) Biotechnology", "Unsupported"),
    79: ("education", "unspecified", "BBA / Bachelor of Business Administration", "Strong"),
    80: ("education", "unspecified", "", "Unsupported"),
    81: ("experience", "unspecified", "10+ years of diversified experience in software sales, cloud sales, B2B, SaaS, lead generation, and project management", "Strong"),
    82: ("experience", "unspecified", "", "Unsupported"),
    83: ("experience", "unspecified", "", "Unsupported"),
    84: ("experience", "unspecified", "Project Manager roles spanning 2011–2022, including enterprise data warehouse implementation", "Strong"),
    85: ("experience", "unspecified", "Enterprise Datawarehouse Implementation & Support Project; managed the Enterprise Datawarehouse Implementation project", "Strong"),
    86: ("experience", "unspecified", "", "Unsupported"),
    87: ("experience", "unspecified", "Key Account Manager from Dec 2022–Present and prior sales/business roles", "Partial"),
    88: ("experience", "unspecified", "", "Unsupported"),
    89: ("experience", "unspecified", "", "Unsupported"),
    90: ("experience", "unspecified", "Power BI and data analytics experience", "Partial"),
    91: ("experience", "unspecified", "", "Unsupported"),
    92: ("experience", "unspecified", "CRM systems including Zendesk, Freshdesk, Salesforce, HubSpot, IGMS and Odoo", "Strong"),
    93: ("experience", "unspecified", "", "Unsupported"),
    94: ("experience", "unspecified", "", "Unsupported"),
    95: ("experience", "unspecified", "", "Unsupported"),
    96: ("experience", "unspecified", "", "Unsupported"),
    97: ("experience", "unspecified", "Business development experience across multiple roles", "Strong"),
    98: ("experience", "unspecified", "", "Unsupported"),
    99: ("experience", "unspecified", "", "Unsupported"),
    100: ("experience", "unspecified", "", "Unsupported"),
    101: ("experience", "unspecified", "", "Unsupported"),
    102: ("experience", "unspecified", "", "Unsupported"),
    103: ("experience", "unspecified", "", "Unsupported"),
    104: ("experience", "unspecified", "Experience less than 1 year", "Unsupported"),
    105: ("experience", "unspecified", "", "Unsupported"),
    106: ("experience", "unspecified", "", "Unsupported"),
    107: ("experience", "unspecified", "Project management and data analytics experience", "Partial"),
    108: ("experience", "unspecified", "", "Unsupported"),
    109: ("experience", "unspecified", "", "Unsupported"),
    110: ("experience", "unspecified", "", "Strong"),
    111: ("tool", "unspecified", "Worked on two projects related to ZOHO CRM and RedMine; Proficient in Stata and Microsoft Word, Excel & PowerPoint", "Strong"),
    112: ("tool", "unspecified", "Using ZOHO CRM for lead management and day-to-day performance analytics", "Partial"),
    113: ("tool", "unspecified", "CRM", "Strong"),
    114: ("tool", "unspecified", "", "Unsupported"),
    115: ("tool", "unspecified", "", "Unsupported"),
    116: ("tool", "unspecified", "HubSpot", "Partial"),
    117: ("tool", "unspecified", "", "Unsupported"),    
    118: ("tool", "unspecified", "", "Unsupported"),
    119: ("tool", "unspecified", "", "Unsupported"),
    120: ("tool", "unspecified", "", "Unsupported"),
    121: ("tool", "unspecified", "", "Unsupported"),
    122: ("tool", "unspecified", "", "Unsupported"),
    123: ("tool", "unspecified", "Microsoft Office (Word, Excel, PowerPoint)", "Partial"),
    124: ("tool", "unspecified", "", "Unsupported"),
    125: ("tool", "unspecified", "Microsoft Word, Excel, PowerPoint, Outlook; CRM systems including Zendesk, Freshdesk, Salesforce, HubSpot, IGMS and Odoo", "Strong"),
    126: ("tool", "unspecified", "Competent user of Microsoft Office", "Partial"),
    127: ("tool", "unspecified", "", "Unsupported"),
    128: ("tool", "unspecified", "Adept in Microsoft Word & PowerPoint", "Partial"),
    129: ("tool", "unspecified", "Using ZOHO CRM for lead management and day-to-day performance analytics", "Partial"),
    130: ("tool", "unspecified", "Well known about MS Office, G-suite, CRM, Salesforce & ERP Software", "Strong"),
    131: ("tool", "unspecified", "", "Unsupported"),
    132: ("tool", "unspecified", "Developed processes on CRM and mastered Monday.com; efficient command on MS Office (Word, Excel, PowerPoint); business tools include Sales Force, Pipe Drive, Monday.com, Bitrix24, Pipelinepro, Propforce", "Strong"),
    133: ("tool", "unspecified", "", "Unsupported"),
    134: ("tool", "unspecified", "", "Unsupported"),
    135: ("tool", "unspecified", "", "Unsupported"),
    136: ("tool", "unspecified", "Created spreadsheets using Microsoft Excel; developed marketing strategies through CRM; skills include CRM, HubSpot and Salesforce", "Strong"),
    137: ("tool", "unspecified", "CRM certification / CRM experience", "Partial"),
    138: ("tool", "unspecified", "", "Unsupported"),
    139: ("tool", "unspecified", "", "Unsupported"),
    140: ("tool", "unspecified", "", "Unsupported"),
    141: ("soft_skill", "unspecified", "Balance of hands-on, management and leadership responsibilities", "Partial"),
    142: ("soft_skill", "unspecified", "Managing total of 15 accounts including end users and channel partners; coordination between marketing, sales, and planning teams", "Partial"),
    143: ("soft_skill", "unspecified", "Conducting successful training for SFDC to Sub Sahara Africa market with more than 17 people; communicating with the Marcom team regarding campaigns", "Strong"),   
    144: ("soft_skill", "unspecified", "I very much believe in teamwork, problem-solving, leadership, and adaptability; Business Development Executive experience involving client communication", "Strong"),
    145: ("soft_skill", "unspecified", "Excellent communication and interpersonal skills", "Strong"),
    146: ("soft_skill", "unspecified", "Excellent communication and interpersonal skills", "Strong"),
    147: ("soft_skill", "unspecified", "Experience coordinating multiple business, sales, and project responsibilities", "Partial"),
    148: ("soft_skill", "unspecified", "Communication with clients; arranging and leading meetings with clients", "Strong"),
    149: ("soft_skill", "unspecified", "Communication; Interpersonal; Team Player; Customer Service and Active Listening", "Strong"),
    150: ("soft_skill", "unspecified", "Communication with clients and customer-facing business development responsibilities", "Strong"),
    151: ("soft_skill", "unspecified", "", "Unsupported"),
    152: ("soft_skill", "unspecified", "Strong interpersonal and communication skills", "Strong"),
    153: ("soft_skill", "unspecified", "", "Unsupported"),
    154: ("soft_skill", "unspecified", "", "Unsupported"),
    155: ("soft_skill", "unspecified", "Client communication and sales closing; team training and client management", "Strong"),
    156: ("soft_skill", "unspecified", "Managed and worked with the team to deliver targets; worked with operations and key accounts to successfully onboard projects", "Strong"),  
    157: ("soft_skill", "unspecified", "Team training; defined direction and set quarterly targets; managed and worked with the team to deliver targets", "Strong"),
    158: ("soft_skill", "unspecified", "", "Unsupported"),
    159: ("soft_skill", "unspecified", "", "Unsupported"),
    160: ("soft_skill", "unspecified", "", "Unsupported"),
    161: ("soft_skill", "unspecified", "", "Unsupported"),
    162: ("soft_skill", "unspecified", "Defined and integrated roles, responsibilities and processes for business team and data management organization; worked on ongoing projects and contracts", "Partial"),
    163: ("soft_skill", "unspecified", "", "Unsupported"),
    164: ("soft_skill", "unspecified", "Strong inter-personal and communication skills; ability to present ideas", "Strong"),   
    165: ("soft_skill", "unspecified", "", "Unsupported"),
    166: ("soft_skill", "unspecified", "", "Unsupported"),
    167: ("soft_skill", "unspecified", "", "Unsupported"),
    168: ("soft_skill", "unspecified", "", "Unsupported"),
    169: ("soft_skill", "unspecified", "", "Unsupported"),
    170: ("soft_skill", "unspecified", "", "Unsupported"),
    171: ("capability", "unspecified", "Used specialized techniques for bargaining and negotiations; strategic planning and business plans that delivered growth", "Strong"),
    172: ("capability", "unspecified", "13+ years in Sales & Marketing, Project & Operations Management, Key Account Management and Client Services; Head of Sales experience", "Strong"),
    173: ("capability", "unspecified", "Business Development Executive generating leads and securing business opportunities; Sales Development Representative engaging international clients; Customer Success experience", "Strong"),
    174: ("capability", "unspecified", "Business Development Executive; managed profiling and bidding; generated leads through LinkedIn; client communication and sales closing", "Strong"),
    175: ("capability", "unspecified", "Data analytical skills; analyzed marketing and financial trends using SQL, Excel and Power BI", "Strong"),
    176: ("capability", "unspecified", "Data Analysis; Planning and Forecasting; Power BI; Microsoft Office and related business tools", "Strong"),
    177: ("capability", "unspecified", "", "Unsupported"),
    178: ("capability", "unspecified", "", "Unsupported"),
    179: ("capability", "unspecified", "", "Unsupported"),
    180: ("capability", "unspecified", "", "Unsupported"),
    181: ("capability", "unspecified", "", "Unsupported"),
    182: ("capability", "unspecified", "", "Unsupported"),
    183: ("capability", "unspecified", "", "Unsupported"),
    184: ("capability", "unspecified", "3 years of experience in Business Development, Business Intelligence and Digital Marketing; client communication and sales closing", "Strong"),
    185: ("capability", "unspecified", "Problem-solving, leadership and adaptability; BI and digital marketing experience involving market research and data visualization", "Partial"),
    186: ("capability", "unspecified", "Business Development Team Lead; Business Strategy; Sales Pipeline Management; Negotiation experience", "Strong"),
    187: ("capability", "unspecified", "Business Development Team Lead and multiple Business Development Executive roles; sales pipeline management", "Strong"),
    188: ("capability", "unspecified", "Business Development Executive; identifying new business opportunities and potential clients through networking and lead generation", "Strong"),
    189: ("capability", "unspecified", "Microsoft Office; Data analysis and sales forecasting", "Strong"),
    190: ("capability", "unspecified", "Analytical software and Power BI evidence not found in the available resume source", "Unsupported"),
    191: ("capability", "unspecified", "", "Unsupported"),
    192: ("capability", "unspecified", "", "Unsupported"),
    193: ("capability", "unspecified", "", "Unsupported"),
    194: ("capability", "unspecified", "Well known about MS Office, G-suite, CRM, Salesforce and ERP Software; data analysis experience", "Strong"),
    195: ("capability", "unspecified", "", "Unsupported"),
    196: ("capability", "unspecified", "Business development experience; identifying and engaging potential clients and lead generation activities", "Strong"),
    197: ("capability", "unspecified", "", "Unsupported"),
    198: ("capability", "unspecified", "", "Unsupported"),
    199: ("capability", "unspecified", "MS Office skills; computer skills and business development experience", "Partial"),
    200: ("capability", "unspecified", "Strategic Planning; Forecasting & Budgeting; comprehensive analysis; Sales Management and Negotiation", "Strong"),
}

for annotation_id, values in annotations.items():
    requirement_type, importance, evidence, label = values

    mask = df["annotation_id"] == str(annotation_id)

    df.loc[mask, "requirement_type"] = requirement_type
    df.loc[mask, "importance"] = importance
    df.loc[mask, "resume_evidence"] = evidence
    df.loc[mask, "label"] = label

df.to_csv(gold_path, index=False)

print(f"Updated {len(annotations)} Gold annotations.")
print("\nLabel distribution:")
print(df["label"].value_counts(dropna=False))

print("\nRequirement-type distribution:")
print(df["requirement_type"].value_counts(dropna=False))